### ISSUE TITLE
Label refactoring

### ISSUE THREAD

**Issue by yue-hua-x** [cse110-sp24-group21/cse110-sp24-group21#32]
Labels need to be refactored so that they're stored as {id, label} instead of just as a list of plaintext labels.

**Comment by HenoHyj** [comment]
Do we ever need to have that one label having both label-name and label-id right now? I completed label searching feature, and I just find out there's the only place we are looking for tasks/entries by the label name. We want that name-id paire because when there's a interface that we can see all tasks/entries group by label, but I didn't see that feature in our webpage design yet.
